"""
process_sprites.py
Processes reference PNG images for the single-screen platformer.
- Removes white/near-white background (BFS from border pixels, threshold 235)
- Auto-crops to character bounds
- Resizes to consistent height (TARGET_H pixels) maintaining aspect ratio
- Encodes as base64 PNG data URL
- Outputs js/sprites_data.js with const SPRITE_DATA = { ... }
"""

import os
import base64
import io
from collections import deque
from PIL import Image

# Map from output key -> source filename
SPRITE_MAP = {
    'champion':      'champion_reference.png',
    'ranger':        'ranger_reference.png',
    'savage':        'savage_reference.png',
    'banditThug':    'bandit_thug_reference.png',
    'banditArcher':  'bandit_archer_reference.png',
    'banditBoss':    'bandit_king_reference.png',
    'goblinWarrior': 'goblin_warrior_reference.png',
    'goblinShaman':  'goblin_shaman_reference.png',
    'goblinBoss':    'goblin_warchief_reference.png',
    'orcBrute':      'orc_brute_reference.png',
    'orcArcher':     'orc_archer_reference.png',
    'orcBoss':       'orc_warlord_reference.png',
}

TARGET_H = 96        # target sprite height in pixels
BG_THRESHOLD = 235   # pixels with all channels >= this are considered background

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR    = os.path.join(SCRIPT_DIR, '..', 'character_references')
OUT_FILE   = os.path.join(SCRIPT_DIR, '..', 'js', 'sprites_data.js')


def remove_background(img):
    """BFS flood fill from border pixels to mark background, then set alpha=0."""
    img = img.convert('RGBA')
    w, h = img.size
    pixels = img.load()

    visited = [[False] * h for _ in range(w)]
    queue = deque()

    def is_bg(r, g, b, a):
        return a < 10 or (r >= BG_THRESHOLD and g >= BG_THRESHOLD and b >= BG_THRESHOLD)

    # Seed from all border pixels
    for x in range(w):
        for y in [0, h - 1]:
            r, g, b, a = pixels[x, y]
            if not visited[x][y] and is_bg(r, g, b, a):
                visited[x][y] = True
                queue.append((x, y))
    for y in range(h):
        for x in [0, w - 1]:
            r, g, b, a = pixels[x, y]
            if not visited[x][y] and is_bg(r, g, b, a):
                visited[x][y] = True
                queue.append((x, y))

    while queue:
        cx, cy = queue.popleft()
        pixels[cx, cy] = (255, 255, 255, 0)
        for nx, ny in [(cx-1,cy),(cx+1,cy),(cx,cy-1),(cx,cy+1)]:
            if 0 <= nx < w and 0 <= ny < h and not visited[nx][ny]:
                r, g, b, a = pixels[nx, ny]
                if is_bg(r, g, b, a):
                    visited[nx][ny] = True
                    queue.append((nx, ny))

    return img


def process_sprite(src_path, target_h=TARGET_H):
    img = Image.open(src_path)
    img = remove_background(img)

    # Auto-crop to character bounds
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)

    # Resize to target height maintaining aspect ratio
    orig_w, orig_h = img.size
    new_h = target_h
    new_w = max(1, round(orig_w * new_h / orig_h))
    img = img.resize((new_w, new_h), Image.LANCZOS)

    # Encode as base64 PNG
    buf = io.BytesIO()
    img.save(buf, format='PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')
    return f'data:image/png;base64,{b64}'


def main():
    entries = []
    for key, filename in SPRITE_MAP.items():
        src_path = os.path.join(SRC_DIR, filename)
        if not os.path.exists(src_path):
            print(f'  MISSING: {src_path}')
            continue
        print(f'  Processing {key} <- {filename}...')
        data_url = process_sprite(src_path)
        kb = len(data_url) // 1024
        print(f'    -> {kb} KB')
        entries.append(f'  {key}: \'{data_url}\'')

    js = '// Auto-generated by tools/process_sprites.py — do not edit manually\n'
    js += 'const SPRITE_DATA = {\n'
    js += ',\n'.join(entries)
    js += '\n};\n'

    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js)

    total_kb = os.path.getsize(OUT_FILE) // 1024
    print(f'\nWrote {OUT_FILE} ({total_kb} KB, {len(entries)} sprites)')


if __name__ == '__main__':
    main()
